import { AgentRole, ProjectKind, RequirementRecord } from '../../shared/types.js';

export interface ScaffoldFile {
  path: string;
  content: string;
}

export interface ScaffoldPlan {
  kind: ProjectKind;
  techStack: string[];
  files: ScaffoldFile[];
  decisions: { title: string; rationale: string; consequences: string[] }[];
}

function requirementsMarkdown(requirements: RequirementRecord[]) {
  return requirements.map((req, index) => `${index + 1}. [${req.status}] (${req.owner}) ${req.text}`).join('\n');
}

function safeJson(value: unknown) {
  return JSON.stringify(value, null, 2);
}

export function createScaffold(kind: ProjectKind, projectName: string, instruction: string, requirements: RequirementRecord[], agents: AgentRole[]): ScaffoldPlan {
  if (kind === 'game') return createGameScaffold(projectName, instruction, requirements, agents);
  if (kind === 'api') return createApiScaffold(projectName, instruction, requirements, agents);
  return createFullStackScaffold(kind, projectName, instruction, requirements, agents);
}

function commonDocs(projectName: string, instruction: string, requirements: RequirementRecord[], agents: AgentRole[]) {
  return [
    {
      path: 'docs/requirements.md',
      content: `# Requirements\n\nForge AI extracted these requirements from the user's specification. Status is updated as the autonomous agent implements and tests features.\n\n## Source instruction\n\n${instruction}\n\n## Tracked requirements\n\n${requirementsMarkdown(requirements)}\n`
    },
    {
      path: 'docs/architecture.md',
      content: `# ${projectName} Architecture\n\n## Specialist agents selected\n\n${agents.map((agent) => `- ${agent}`).join('\n')}\n\n## Engineering principles\n\n- Real codebase with editable source files and tests.\n- Secure-by-default environment variable handling.\n- Production build must pass before deployment.\n- Integrations are wired through server-side adapters rather than hard-coded secrets.\n- Requirements remain traceable in docs/requirements.md.\n`
    },
    {
      path: '.env.example',
      content: `# Generated by Forge AI. Copy to .env.local for local development.\n# Never commit real secrets.\nSUPABASE_URL=\nSUPABASE_ANON_KEY=\nSUPABASE_SERVICE_ROLE_KEY=\nSUPABASE_DB_URL=\nSTRIPE_SECRET_KEY=\nSTRIPE_WEBHOOK_SECRET=\nRESEND_API_KEY=\nVERCEL_PROJECT_ID=\n`
    },
    {
      path: '.gitignore',
      content: `node_modules\ndist\nbuild\n.data\n.env\n.env.*\n!.env.example\ncoverage\n.DS_Store\n*.log\n`
    }
  ];
}

function createFullStackScaffold(kind: ProjectKind, projectName: string, instruction: string, requirements: RequirementRecord[], agents: AgentRole[]): ScaffoldPlan {
  const capabilities = {
    projectName,
    instruction,
    kind,
    generatedAt: new Date().toISOString(),
    requirements: requirements.map((req) => ({ id: req.id, text: req.text, owner: req.owner }))
  };
  const requirementRows = requirements.map((req) => ({ id: req.id, text: req.text, owner: req.owner, status: req.status }));
  const appName = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const files: ScaffoldFile[] = [
    ...commonDocs(projectName, instruction, requirements, agents),
    {
      path: 'package.json',
      content: safeJson({
        name: appName,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'concurrently -k "vite --host 0.0.0.0" "tsx server/index.ts"',
          'dev:api': 'tsx server/index.ts',
          build: 'tsc --noEmit && vite build',
          typecheck: 'tsc --noEmit',
          test: 'vitest run',
          lint: 'tsc --noEmit'
        },
        dependencies: {
          '@supabase/supabase-js': 'latest',
          '@vitejs/plugin-react': 'latest',
          concurrently: 'latest',
          express: '^4.18.3',
          react: 'latest',
          'react-dom': 'latest',
          vite: 'latest',
          zod: 'latest'
        },
        devDependencies: {
          '@types/express': '^4.17.21',
          '@types/node': 'latest',
          '@types/react': 'latest',
          '@types/react-dom': 'latest',
          tsx: 'latest',
          typescript: 'latest',
          vitest: 'latest'
        }
      })
    },
    {
      path: 'index.html',
      content: [
        '<!doctype html>',
        '<html lang="en">',
        '  <head>',
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        `    <title>${projectName}</title>`,
        '  </head>',
        '  <body>',
        '    <div id="root"></div>',
        '    <script type="module" src="/src/main.tsx"></script>',
        '  </body>',
        '</html>'
      ].join('\n') + '\n'
    },
    {
      path: 'tsconfig.json',
      content: safeJson({
        compilerOptions: {
          target: 'ES2022',
          useDefineForClassFields: true,
          lib: ['DOM', 'DOM.Iterable', 'ES2022'],
          allowJs: false,
          skipLibCheck: true,
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          strict: true,
          forceConsistentCasingInFileNames: true,
          module: 'ESNext',
          moduleResolution: 'Bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'react-jsx',
          types: ['node', 'vite/client']
        },
        include: ['src', 'server', 'tests']
      })
    },
    {
      path: 'vite.config.ts',
      content: [
        "import { defineConfig } from 'vite';",
        "import react from '@vitejs/plugin-react';",
        '',
        'const apiPort = Number(process.env.API_PORT) || 8787;',
        '',
        'export default defineConfig({',
        '  plugins: [react()],',
        "  server: { host: '0.0.0.0', port: Number(process.env.PORT) || 5173, allowedHosts: true, proxy: { '/api': `http://localhost:${apiPort}`, '/health': `http://localhost:${apiPort}` } },",
        "  preview: { host: '0.0.0.0', allowedHosts: true },",
        "  test: { environment: 'node' }",
        '});'
      ].join('\n') + '\n'
    },
    { path: 'src/vite-env.d.ts', content: '/// <reference types="vite/client" />\n' },
    {
      path: 'src/domain/capabilities.ts',
      content: [
        `export const forgeCapabilities = ${safeJson(capabilities)} as const;`,
        '',
        `export const extractedRequirements = ${safeJson(requirementRows)} as const;`,
        '',
        'export function requirementCoverage() {',
        '  return extractedRequirements.map((requirement) => ({',
        '    ...requirement,',
        "    implementedBy: ['src/App.tsx', 'server/index.ts', 'server/auth.ts', 'server/store.ts', 'server/supabase.ts', 'supabase/migrations'],",
        "    qualityBar: 'Real API, persisted data, loading states, errors, tests, build, and deployment gate.'",
        '  }));',
        '}'
      ].join('\n') + '\n'
    },
    {
      path: 'src/types.ts',
      content: [
        'export interface AuthUser {',
        '  id: string;',
        '  email: string;',
        '}',
        '',
        'export interface FeatureItem {',
        '  id: string;',
        '  ownerId: string;',
        '  title: string;',
        "  status: 'planned' | 'building' | 'done';",
        '  createdAt: string;',
        '}',
        '',
        'export interface HealthResponse {',
        '  ok: boolean;',
        '  service: string;',
        "  backend: 'supabase' | 'local-json';",
        '  checkedAt: string;',
        '}'
      ].join('\n') + '\n'
    },
    {
      path: 'src/lib/apiClient.ts',
      content: [
        'export interface ApiResult<T> { data?: T; error?: string }',
        '',
        'export async function apiRequest<T>(path: string, init?: RequestInit): Promise<ApiResult<T>> {',
        '  try {',
        '    const response = await fetch(path, {',
        '      ...init,',
        "      headers: { 'content-type': 'application/json', ...(init?.headers || {}) }",
        '    });',
        '    const json = await response.json().catch(() => ({}));',
        "    if (!response.ok) return { error: json.error || 'Request failed' };",
        '    return { data: json as T };',
        '  } catch (error) {',
        '    return { error: error instanceof Error ? error.message : String(error) };',
        '  }',
        '}'
      ].join('\n') + '\n'
    },
    {
      path: 'src/App.tsx',
      content: [
        "import { FormEvent, useEffect, useMemo, useState } from 'react';",
        "import { forgeCapabilities, requirementCoverage } from './domain/capabilities';",
        "import { apiRequest } from './lib/apiClient';",
        "import type { AuthUser, FeatureItem, HealthResponse } from './types';",
        "import './styles.css';",
        '',
        'export default function App() {',
        '  const [health, setHealth] = useState<HealthResponse | null>(null);',
        '  const [user, setUser] = useState<AuthUser | null>(null);',
        '  const [features, setFeatures] = useState<FeatureItem[]>([]);',
        "  const [email, setEmail] = useState('demo@example.com');",
        "  const [password, setPassword] = useState('password123');",
        "  const [title, setTitle] = useState('Protected customer dashboard');",
        "  const [error, setError] = useState('');",
        '  const [loading, setLoading] = useState(true);',
        '  const coverage = useMemo(() => requirementCoverage(), []);',
        '',
        '  async function refresh() {',
        "    setError('');",
        '    setLoading(true);',
        "    const [healthResult, meResult] = await Promise.all([apiRequest<HealthResponse>('/health'), apiRequest<{ user: AuthUser | null }>('/api/auth/me')]);",
        '    if (healthResult.error) setError(healthResult.error); else setHealth(healthResult.data || null);',
        '    if (!meResult.error) setUser(meResult.data?.user || null);',
        '    if (meResult.data?.user) {',
        "      const featuresResult = await apiRequest<FeatureItem[]>('/api/features');",
        '      if (featuresResult.error) setError(featuresResult.error); else setFeatures(featuresResult.data || []);',
        '    } else {',
        '      setFeatures([]);',
        '    }',
        '    setLoading(false);',
        '  }',
        '',
        '  useEffect(() => { void refresh(); }, []);',
        '',
        "  async function auth(path: '/api/auth/signup' | '/api/auth/login') {",
        "    setError('');",
        "    const result = await apiRequest<{ user: AuthUser }>(path, { method: 'POST', body: JSON.stringify({ email, password }) });",
        '    if (result.error) setError(result.error); else await refresh();',
        '  }',
        '',
        '  async function logout() {',
        "    await apiRequest('/api/auth/logout', { method: 'POST' });",
        '    await refresh();',
        '  }',
        '',
        '  async function addFeature(event: FormEvent) {',
        '    event.preventDefault();',
        '    if (!title.trim()) return;',
        "    setError('');",
        "    const result = await apiRequest<FeatureItem>('/api/features', { method: 'POST', body: JSON.stringify({ title }) });",
        "    if (result.error) setError(result.error); else { setTitle(''); await refresh(); }",
        '  }',
        '',
        '  return (',
        '    <main className="app">',
        '      <section className="hero">',
        '        <div>',
        '          <p className="eyebrow">Real full-stack auth app generated by Forge</p>',
        '          <h1>{forgeCapabilities.projectName}</h1>',
        '          <p>Signup and login are real. The backend creates password hashes, secure session cookies, protected APIs, persisted user-owned data, and can switch to Supabase when connected.</p>',
        '        </div>',
        '        <div className="backend-card">',
        '          <span>Backend</span>',
        "          <strong>{health?.backend || 'checking...'}</strong>",
        "          <small>{user ? `Signed in as ${user.email}` : 'Not signed in'}</small>",
        '        </div>',
        '      </section>',
        '',
        '      <section className="workspace">',
        '        <article className="panel">',
        '          <h2>Authentication</h2>',
        '          <div className="auth-grid">',
        '            <input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="email" />',
        '            <input value={password} onChange={(event) => setPassword(event.target.value)} placeholder="password" type="password" />',
        "            <button onClick={() => auth('/api/auth/signup')}>Sign up</button>",
        "            <button onClick={() => auth('/api/auth/login')}>Log in</button>",
        '            <button onClick={logout}>Log out</button>',
        '          </div>',
        '          {loading && <p className="state">Loading backend data...</p>}',
        '          {error && <p className="error">{error}</p>}',
        '        </article>',
        '',
        '        <article className="panel primary-panel">',
        '          <h2>Protected feature database</h2>',
        '          <form onSubmit={addFeature}>',
        '            <input disabled={!user} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Add protected feature" />',
        '            <button disabled={!user}>Add feature</button>',
        '          </form>',
        '          {!user && <p className="state">Sign up or log in to use the protected API.</p>}',
        '          <div className="features">',
        '            {features.map((feature) => (',
        '              <div key={feature.id} className="feature">',
        '                <strong>{feature.title}</strong>',
        '                <span>{feature.status}</span>',
        '                <small>{new Date(feature.createdAt).toLocaleString()}</small>',
        '              </div>',
        '            ))}',
        '          </div>',
        '        </article>',
        '      </section>',
        '',
        '      <article className="panel requirements-panel">',
        '        <h2>Requirement coverage</h2>',
        '        <div className="requirements">',
        '          {coverage.map((item) => <p key={item.id}><strong>{item.owner}</strong>{item.text}</p>)}',
        '        </div>',
        '      </article>',
        '    </main>',
        '  );',
        '}',
      ].join('\n') + '\n'
    },
    {
      path: 'src/main.tsx',
      content: [
        "import React from 'react';",
        "import { createRoot } from 'react-dom/client';",
        "import App from './App';",
        '',
        "createRoot(document.getElementById('root')!).render(",
        '  <React.StrictMode>',
        '    <App />',
        '  </React.StrictMode>',
        ');'
      ].join('\n') + '\n'
    },
    {
      path: 'src/styles.css',
      content: [
        ':root { color-scheme: dark; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #050816; color: #f8fbff; }',
        '* { box-sizing: border-box; }',
        'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at 20% 0%, rgba(14,165,233,.35), transparent 28rem), radial-gradient(circle at 100% 20%, rgba(168,85,247,.25), transparent 28rem), #050816; }',
        '.app { width: min(1120px, calc(100% - 32px)); margin: 0 auto; padding: 40px 0; }',
        '.hero { display: grid; grid-template-columns: 1fr 260px; gap: 18px; align-items: stretch; padding: 30px; border: 1px solid rgba(148,163,184,.22); border-radius: 32px; background: linear-gradient(135deg, rgba(15,23,42,.92), rgba(30,41,59,.72)); box-shadow: 0 30px 90px rgba(0,0,0,.35); }',
        '.eyebrow { margin: 0 0 10px; color: #67e8f9; text-transform: uppercase; letter-spacing: .18em; font-weight: 900; font-size: 12px; }',
        'h1 { margin: 0; font-size: clamp(42px, 8vw, 88px); line-height: .9; letter-spacing: -.06em; }',
        '.hero p { color: #c6d6ef; font-size: 18px; line-height: 1.6; max-width: 760px; }',
        '.backend-card, .panel { border: 1px solid rgba(148,163,184,.18); border-radius: 24px; background: rgba(2,6,23,.45); padding: 20px; }',
        '.backend-card { display: grid; align-content: center; gap: 10px; }',
        '.backend-card span, small { color: #94a3b8; }',
        '.backend-card strong { font-size: 28px; color: #bbf7d0; }',
        '.workspace { display: grid; grid-template-columns: .85fr 1.15fr; gap: 18px; margin-top: 18px; }',
        '.requirements-panel { margin-top: 18px; }',
        '.panel h2 { margin-top: 0; }',
        '.auth-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }',
        '.auth-grid button:last-child { grid-column: 1 / -1; background: rgba(148,163,184,.18); color: #e2e8f0; }',
        'form { display: grid; grid-template-columns: 1fr auto; gap: 10px; margin-bottom: 14px; }',
        'input { border: 1px solid rgba(148,163,184,.22); border-radius: 16px; background: rgba(15,23,42,.85); color: #fff; padding: 13px 14px; }',
        'button { border: 0; border-radius: 16px; padding: 13px 16px; font-weight: 900; cursor: pointer; color: #020617; background: linear-gradient(135deg, #38bdf8, #a78bfa); }',
        'button:disabled, input:disabled { opacity: .55; cursor: not-allowed; }',
        '.features, .requirements { display: grid; gap: 10px; max-height: 460px; overflow: auto; }',
        '.feature, .requirements p { margin: 0; display: grid; gap: 5px; padding: 13px; border: 1px solid rgba(148,163,184,.14); border-radius: 16px; background: rgba(15,23,42,.56); }',
        '.feature span { width: max-content; border-radius: 999px; padding: 4px 9px; background: rgba(34,197,94,.14); color: #bbf7d0; font-size: 12px; }',
        '.requirements strong { color: #7dd3fc; display: block; margin-bottom: 4px; }',
        '.state { color: #bfdbfe; }',
        '.error { color: #fecaca; border: 1px solid rgba(248,113,113,.35); background: rgba(127,29,29,.25); padding: 10px; border-radius: 14px; }',
        '@media (max-width: 820px) { .hero, .workspace, .auth-grid { grid-template-columns: 1fr; } }',
      ].join('\n') + '\n'
    },
    {
      path: 'server/auth.ts',
      content: [
        "import crypto from 'node:crypto';",
        "import fs from 'node:fs';",
        "import path from 'node:path';",
        '',
        'export interface AuthUser { id: string; email: string; passwordHash: string; salt: string; createdAt: string }',
        'interface Session { tokenHash: string; userId: string; expiresAt: string }',
        'interface AuthState { users: AuthUser[]; sessions: Session[] }',
        '',
        "const dataDir = path.resolve(process.cwd(), '.data');",
        "const authFile = path.join(dataDir, 'auth.json');",
        '',
        'function readState(): AuthState {',
        '  fs.mkdirSync(dataDir, { recursive: true });',
        '  if (!fs.existsSync(authFile)) fs.writeFileSync(authFile, JSON.stringify({ users: [], sessions: [] }, null, 2));',
        "  return JSON.parse(fs.readFileSync(authFile, 'utf8')) as AuthState;",
        '}',
        '',
        'function writeState(state: AuthState) {',
        '  fs.writeFileSync(authFile, JSON.stringify(state, null, 2));',
        '}',
        '',
        'function hash(value: string, salt: string) {',
        "  return crypto.scryptSync(value, salt, 64).toString('hex');",
        '}',
        '',
        'function publicUser(user: AuthUser) {',
        '  return { id: user.id, email: user.email };',
        '}',
        '',
        'export function signupLocal(email: string, password: string) {',
        '  const normalized = email.trim().toLowerCase();',
        "  if (!/^\\S+@\\S+\\.\\S+$/.test(normalized)) throw new Error('A valid email is required.');",
        "  if (password.length < 8) throw new Error('Password must be at least 8 characters.');",
        '  const state = readState();',
        "  if (state.users.some((user) => user.email === normalized)) throw new Error('An account already exists for this email.');",
        "  const salt = crypto.randomBytes(16).toString('hex');",
        '  const user: AuthUser = { id: crypto.randomUUID(), email: normalized, passwordHash: hash(password, salt), salt, createdAt: new Date().toISOString() };',
        '  state.users.push(user);',
        '  writeState(state);',
        '  return publicUser(user);',
        '}',
        '',
        'export function loginLocal(email: string, password: string) {',
        '  const normalized = email.trim().toLowerCase();',
        '  const state = readState();',
        '  const user = state.users.find((candidate) => candidate.email === normalized);',
        "  if (!user || hash(password, user.salt) !== user.passwordHash) throw new Error('Invalid email or password.');",
        '  return publicUser(user);',
        '}',
        '',
        'export function createSession(userId: string) {',
        '  const state = readState();',
        "  const token = crypto.randomBytes(32).toString('base64url');",
        "  const tokenHash = crypto.createHash('sha256').update(token).digest('hex');",
        '  const expiresAt = new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString();',
        '  state.sessions = state.sessions.filter((session) => new Date(session.expiresAt).getTime() > Date.now());',
        '  state.sessions.push({ tokenHash, userId, expiresAt });',
        '  writeState(state);',
        '  return token;',
        '}',
        '',
        'export function userFromSession(token?: string) {',
        '  if (!token) return null;',
        '  const state = readState();',
        "  const tokenHash = crypto.createHash('sha256').update(token).digest('hex');",
        '  const session = state.sessions.find((item) => item.tokenHash === tokenHash && new Date(item.expiresAt).getTime() > Date.now());',
        '  const user = session ? state.users.find((candidate) => candidate.id === session.userId) : undefined;',
        '  return user ? publicUser(user) : null;',
        '}',
        '',
        'export function destroySession(token?: string) {',
        '  if (!token) return;',
        '  const state = readState();',
        "  const tokenHash = crypto.createHash('sha256').update(token).digest('hex');",
        '  state.sessions = state.sessions.filter((session) => session.tokenHash !== tokenHash);',
        '  writeState(state);',
        '}',
      ].join('\n') + '\n'
    },
    {
      path: 'server/store.ts',
      content: [
        "import fs from 'node:fs';",
        "import path from 'node:path';",
        '',
        "export interface FeatureItem { id: string; ownerId: string; title: string; status: 'planned' | 'building' | 'done'; createdAt: string }",
        '',
        "const dataDir = path.resolve(process.cwd(), '.data');",
        "const dataFile = path.join(dataDir, 'features.json');",
        '',
        'function readFeatures(): FeatureItem[] {',
        '  fs.mkdirSync(dataDir, { recursive: true });',
        '  if (!fs.existsSync(dataFile)) fs.writeFileSync(dataFile, JSON.stringify([], null, 2));',
        "  return JSON.parse(fs.readFileSync(dataFile, 'utf8')) as FeatureItem[];",
        '}',
        '',
        'function writeFeatures(features: FeatureItem[]) {',
        '  fs.writeFileSync(dataFile, JSON.stringify(features, null, 2));',
        '}',
        '',
        'export function listLocalFeatures(ownerId: string): FeatureItem[] {',
        '  return readFeatures().filter((feature) => feature.ownerId === ownerId);',
        '}',
        '',
        'export function createLocalFeature(ownerId: string, title: string): FeatureItem {',
        '  const features = readFeatures();',
        "  const feature: FeatureItem = { id: crypto.randomUUID(), ownerId, title, status: 'planned', createdAt: new Date().toISOString() };",
        '  features.unshift(feature);',
        '  writeFeatures(features);',
        '  return feature;',
        '}',
      ].join('\n') + '\n'
    },
    {
      path: 'server/supabase.ts',
      content: [
        "import { createClient } from '@supabase/supabase-js';",
        "import type { FeatureItem } from './store';",
        '',
        'function client() {',
        '  const url = process.env.SUPABASE_URL;',
        '  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;',
        '  if (!url || !key) return null;',
        '  return createClient(url, key, { auth: { persistSession: false } });',
        '}',
        '',
        'export function supabaseConfigured() { return Boolean(client()); }',
        '',
        'export async function listSupabaseFeatures(ownerId: string): Promise<FeatureItem[] | null> {',
        '  const supabase = client();',
        '  if (!supabase) return null;',
        "  const { data, error } = await supabase.from('features').select('id,owner_id,title,status,created_at').eq('owner_id', ownerId).order('created_at', { ascending: false });",
        '  if (error) throw error;',
        '  return (data || []).map((row) => ({ id: row.id, ownerId: row.owner_id, title: row.title, status: row.status, createdAt: row.created_at }));',
        '}',
        '',
        'export async function createSupabaseFeature(ownerId: string, title: string): Promise<FeatureItem | null> {',
        '  const supabase = client();',
        '  if (!supabase) return null;',
        "  const { data, error } = await supabase.from('features').insert({ owner_id: ownerId, title, status: 'planned' }).select('id,owner_id,title,status,created_at').single();",
        '  if (error) throw error;',
        '  return { id: data.id, ownerId: data.owner_id, title: data.title, status: data.status, createdAt: data.created_at };',
        '}',
      ].join('\n') + '\n'
    },
    {
      path: 'server/index.ts',
      content: [
        "import express from 'express';",
        "import { z } from 'zod';",
        "import { createSession, destroySession, loginLocal, signupLocal, userFromSession } from './auth';",
        "import { createLocalFeature, listLocalFeatures } from './store';",
        "import { createSupabaseFeature, listSupabaseFeatures, supabaseConfigured } from './supabase';",
        '',
        'const app = express();',
        'const port = Number(process.env.API_PORT || 8787);',
        'const authInput = z.object({ email: z.string().email(), password: z.string().min(8) });',
        'const featureInput = z.object({ title: z.string().min(1).max(140) });',
        '',
        'type PublicUser = { id: string; email: string };',
        'type AuthedRequest = express.Request & { user?: PublicUser };',
        '',
        "app.use(express.json({ limit: '1mb' }));",
        '',
        'function cookies(req: express.Request) {',
        "  return Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map((part) => { const [key, ...value] = part.trim().split('='); return [key, decodeURIComponent(value.join('='))]; }));",
        '}',
        '',
        'function sessionCookie(token: string, maxAge: number) {',
        "  return `forge_session=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`;",
        '}',
        '',
        'function requireAuth(req: AuthedRequest, res: express.Response, next: express.NextFunction) {',
        '  const user = userFromSession(cookies(req).forge_session);',
        "  if (!user) { res.status(401).json({ error: 'Authentication required.' }); return; }",
        '  req.user = user;',
        '  next();',
        '}',
        '',
        "app.get('/health', (_req, res) => {",
        `  res.json({ ok: true, service: '${projectName}', backend: supabaseConfigured() ? 'supabase' : 'local-json', checkedAt: new Date().toISOString() });`,
        '});',
        '',
        "app.post('/api/auth/signup', (req, res) => {",
        '  const parsed = authInput.safeParse(req.body);',
        "  if (!parsed.success) { res.status(400).json({ error: 'Invalid signup input', issues: parsed.error.issues }); return; }",
        '  try {',
        '    const user = signupLocal(parsed.data.email, parsed.data.password);',
        '    const token = createSession(user.id);',
        "    res.setHeader('Set-Cookie', sessionCookie(token, 60 * 60 * 24 * 7));",
        '    res.status(201).json({ user });',
        '  } catch (error) {',
        "    res.status(400).json({ error: error instanceof Error ? error.message : 'Signup failed' });",
        '  }',
        '});',
        '',
        "app.post('/api/auth/login', (req, res) => {",
        '  const parsed = authInput.safeParse(req.body);',
        "  if (!parsed.success) { res.status(400).json({ error: 'Invalid login input', issues: parsed.error.issues }); return; }",
        '  try {',
        '    const user = loginLocal(parsed.data.email, parsed.data.password);',
        '    const token = createSession(user.id);',
        "    res.setHeader('Set-Cookie', sessionCookie(token, 60 * 60 * 24 * 7));",
        '    res.json({ user });',
        '  } catch (error) {',
        "    res.status(401).json({ error: error instanceof Error ? error.message : 'Login failed' });",
        '  }',
        '});',
        '',
        "app.post('/api/auth/logout', (req, res) => {",
        '  destroySession(cookies(req).forge_session);',
        "  res.setHeader('Set-Cookie', sessionCookie('', 0));",
        '  res.json({ ok: true });',
        '});',
        '',
        "app.get('/api/auth/me', (req, res) => {",
        '  res.json({ user: userFromSession(cookies(req).forge_session) });',
        '});',
        '',
        "app.get('/api/features', requireAuth, async (req: AuthedRequest, res, next) => {",
        '  try {',
        '    const ownerId = req.user!.id;',
        '    res.json((await listSupabaseFeatures(ownerId)) || listLocalFeatures(ownerId));',
        '  } catch (error) { next(error); }',
        '});',
        '',
        "app.post('/api/features', requireAuth, async (req: AuthedRequest, res, next) => {",
        '  try {',
        '    const parsed = featureInput.safeParse(req.body);',
        "    if (!parsed.success) { res.status(400).json({ error: 'Invalid feature title', issues: parsed.error.issues }); return; }",
        '    const ownerId = req.user!.id;',
        '    res.status(201).json((await createSupabaseFeature(ownerId, parsed.data.title)) || createLocalFeature(ownerId, parsed.data.title));',
        '  } catch (error) { next(error); }',
        '});',
        '',
        'app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {',
        '  console.error(err);',
        "  res.status(500).json({ error: 'Backend operation failed', details: err.message });",
        '});',
        '',
        "app.listen(port, '0.0.0.0', () => console.log(`API listening on http://0.0.0.0:${port}`));",
      ].join('\n') + '\n'
    },
    {
      path: 'docs/fullstack.md',
      content: [
        '# Real full-stack authentication behavior',
        '',
        '- The React UI calls `/health`, `/api/auth/signup`, `/api/auth/login`, `/api/auth/logout`, `/api/auth/me`, `GET /api/features`, and `POST /api/features`.',
        '- The Express backend hashes passwords with Node `crypto.scryptSync`, stores HttpOnly session cookies, protects feature APIs, and persists user-owned records locally in `.data` for development.',
        '- If `SUPABASE_URL` and server-only `SUPABASE_SERVICE_ROLE_KEY` are configured, feature data switches to the real Supabase `features` table.',
        '- SQL migrations are written in `supabase/migrations` for PostgreSQL/RLS review and can be applied by Forge when `SUPABASE_DB_URL` is connected.',
        '- Secrets are never embedded in frontend code. Service-role and database connection credentials stay server-side.',
        '- `npm run build` and `npm test` must pass before publish/deploy.',
      ].join('\n') + '\n'
    },
    {
      path: 'tests/fullstack.test.ts',
      content: [
        "import { describe, expect, it } from 'vitest';",
        "import { createSession, loginLocal, signupLocal, userFromSession } from '../server/auth';",
        "import { createLocalFeature, listLocalFeatures } from '../server/store';",
        "import { requirementCoverage } from '../src/domain/capabilities';",
        '',
        "describe('full-stack generated app', () => {",
        "  it('implements real local authentication and protected persistence', () => {",
        '    const email = `user-${Date.now()}-${Math.random().toString(16).slice(2)}@example.com`;',
        "    const user = signupLocal(email, 'password123');",
        "    expect(loginLocal(email, 'password123').id).toBe(user.id);",
        '    const token = createSession(user.id);',
        '    expect(userFromSession(token)?.email).toBe(email);',
        "    createLocalFeature(user.id, 'Protected item');",
        "    expect(listLocalFeatures(user.id).some((feature) => feature.title === 'Protected item')).toBe(true);",
        '  });',
        '',
        "  it('links every requirement to real implementation evidence', () => {",
        '    const coverage = requirementCoverage();',
        '    expect(coverage.length).toBeGreaterThan(0);',
        "    expect(coverage.every((item) => item.implementedBy.some((file) => file.includes('server/')))).toBe(true);",
        '  });',
        '});',
      ].join('\n') + '\n'
    }
  ];
  return {
    kind,
    techStack: ['React', 'TypeScript', 'Vite', 'Node.js', 'Express', 'Zod', 'Supabase-ready PostgreSQL', 'Vitest'],
    files,
    decisions: [
      {
        title: 'Generate a working full-stack app rather than a mock page',
        rationale: 'The UI performs real HTTP operations against an Express API and data persists locally or in Supabase when configured.',
        consequences: ['Preview demonstrates actual backend behavior.', 'Supabase can be enabled without exposing service-role credentials to browser code.']
      },
      {
        title: 'Use local JSON persistence as an honest development fallback',
        rationale: 'A generated app should work immediately without external credentials while clearly switching to Supabase when configured.',
        consequences: ['No fake database UI.', 'Production deployment can be blocked until real provider credentials and RLS are configured.']
      }
    ]
  };
}

function createApiScaffold(projectName: string, instruction: string, requirements: RequirementRecord[], agents: AgentRole[]): ScaffoldPlan {
  const files: ScaffoldFile[] = [
    ...commonDocs(projectName, instruction, requirements, agents),
    {
      path: 'package.json',
      content: safeJson({
        name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'tsx src/server.ts',
          build: 'tsc -p tsconfig.json',
          start: 'node dist/server.js',
          typecheck: 'tsc --noEmit',
          test: 'vitest run',
          lint: 'tsc --noEmit'
        },
        dependencies: { express: '^4.18.3', zod: 'latest' },
        devDependencies: { '@types/express': '^4.17.21', '@types/node': 'latest', typescript: 'latest', tsx: 'latest', vitest: 'latest' }
      })
    },
    {
      path: 'tsconfig.json',
      content: safeJson({ compilerOptions: { target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', strict: true, esModuleInterop: true, outDir: 'dist', rootDir: 'src', types: ['node'] }, include: ['src', 'tests'] })
    },
    {
      path: 'src/server.ts',
      content: `import express from 'express';\nimport { z } from 'zod';\n\nconst app = express();\nconst port = Number(process.env.PORT || 8787);\napp.use(express.json({ limit: '1mb' }));\n\nconst requestSchema = z.object({ instruction: z.string().min(1).max(20_000) });\n\napp.get('/health', (_req, res) => res.json({ ok: true, service: '${projectName}', time: new Date().toISOString() }));\n\napp.post('/api/tasks', (req, res) => {\n  const parsed = requestSchema.safeParse(req.body);\n  if (!parsed.success) {\n    res.status(400).json({ error: 'Invalid request', issues: parsed.error.issues });\n    return;\n  }\n  res.status(202).json({ accepted: true, instruction: parsed.data.instruction, next: 'Queue this task into a worker for production workloads.' });\n});\n\napp.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {\n  console.error(err);\n  res.status(500).json({ error: 'Internal server error' });\n});\n\napp.listen(port, '0.0.0.0', () => console.log(\`API listening on http://0.0.0.0:\${port}\`));\n`
    },
    {
      path: 'tests/api.test.ts',
      content: `import { describe, expect, it } from 'vitest';\n\ndescribe('api contract', () => {\n  it('documents non-empty extracted requirements', () => {\n    const requirements = ${safeJson(requirements.map((req) => req.text))};\n    expect(requirements.length).toBeGreaterThan(0);\n    expect(requirements.every((item) => item.length > 0)).toBe(true);\n  });\n});\n`
    }
  ];
  return {
    kind: 'api',
    techStack: ['Node.js', 'Express', 'TypeScript', 'Zod', 'Vitest'],
    files,
    decisions: [
      { title: 'Use Express with strict request validation', rationale: 'Backend/API requests need explicit schemas and safe error handling.', consequences: ['Endpoints can be expanded into worker-backed autonomous workflows.', 'Invalid input fails with 400 rather than reaching business logic.'] }
    ]
  };
}

function createGameScaffold(projectName: string, instruction: string, requirements: RequirementRecord[], agents: AgentRole[]): ScaffoldPlan {
  const files: ScaffoldFile[] = [
    ...commonDocs(projectName, instruction, requirements, agents),
    {
      path: 'package.json',
      content: safeJson({
        name: projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: { dev: 'vite --host 0.0.0.0', build: 'tsc --noEmit && vite build', typecheck: 'tsc --noEmit', test: 'vitest run', lint: 'tsc --noEmit' },
        dependencies: { vite: 'latest', typescript: 'latest' },
        devDependencies: { '@types/node': 'latest', vitest: 'latest' }
      })
    },
    {
      path: 'index.html',
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${projectName}</title>\n  </head>\n  <body>\n    <canvas id="game" width="960" height="540" aria-label="${projectName} playable canvas"></canvas>\n    <div id="hud"></div>\n    <script type="module" src="/src/main.ts"></script>\n  </body>\n</html>\n`
    },
    {
      path: 'tsconfig.json',
      content: safeJson({ compilerOptions: { target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true, lib: ['DOM', 'ES2022'], skipLibCheck: true, noEmit: true }, include: ['src', 'tests'] })
    },
    {
      path: 'vite.config.ts',
      content: `import { defineConfig } from 'vite';\nexport default defineConfig({ server: { host: '0.0.0.0', port: Number(process.env.PORT) || 5173, allowedHosts: true }, preview: { host: '0.0.0.0', allowedHosts: true }, test: { environment: 'node' } });\n`
    },
    {
      path: 'src/vite-env.d.ts',
      content: `/// <reference types="vite/client" />\n`
    },
    {
      path: 'src/game/types.ts',
      content: `export type Vec2 = { x: number; y: number };\nexport type EntityKind = 'player' | 'enemy' | 'projectile' | 'loot';\nexport interface Entity { id: string; kind: EntityKind; pos: Vec2; vel: Vec2; radius: number; hp: number; maxHp: number; damage: number; color: string; cooldown: number; }\nexport interface Tile { x: number; y: number; wall: boolean; seen: boolean; }\nexport interface GameState { seed: number; width: number; height: number; tileSize: number; tiles: Tile[]; player: Entity; enemies: Entity[]; loot: Entity[]; projectiles: Entity[]; inventory: string[]; xp: number; level: number; messages: string[]; }\n`
    },
    {
      path: 'src/game/world.ts',
      content: `import type { Entity, GameState, Tile } from './types';\n\nfunction rng(seed: number) {\n  let value = seed >>> 0;\n  return () => {\n    value = (value * 1664525 + 1013904223) >>> 0;\n    return value / 0xffffffff;\n  };\n}\n\nexport function createWorld(seed = Date.now()): GameState {\n  const random = rng(seed);\n  const width = 48;\n  const height = 28;\n  const tileSize = 32;\n  const tiles: Tile[] = [];\n  for (let y = 0; y < height; y++) {\n    for (let x = 0; x < width; x++) {\n      const border = x === 0 || y === 0 || x === width - 1 || y === height - 1;\n      const chamber = x > 4 && x < 18 && y > 5 && y < 18;\n      const hall = (y === 12 && x > 8 && x < 40) || (x === 34 && y > 6 && y < 23);\n      tiles.push({ x, y, wall: border || (!chamber && !hall && random() > 0.72), seen: false });\n    }\n  }\n  const player = makeEntity('player', 'player', 8 * tileSize, 12 * tileSize, '#38bdf8');\n  const enemies: Entity[] = Array.from({ length: 14 }, (_, index) => makeEntity(\`enemy-\${index}\`, 'enemy', (20 + Math.floor(random() * 20)) * tileSize, (7 + Math.floor(random() * 15)) * tileSize, '#fb7185'));\n  const loot: Entity[] = Array.from({ length: 8 }, (_, index) => ({ ...makeEntity(\`loot-\${index}\`, 'loot', (10 + Math.floor(random() * 30)) * tileSize, (5 + Math.floor(random() * 18)) * tileSize, '#facc15'), hp: 1 }));\n  return { seed, width, height, tileSize, tiles, player, enemies, loot, projectiles: [], inventory: [], xp: 0, level: 1, messages: ['Explore the procedural ruin. WASD move, click to attack, E saves.'] };\n}\n\nfunction makeEntity(id: string, kind: Entity['kind'], x: number, y: number, color: string): Entity {\n  return { id, kind, pos: { x, y }, vel: { x: 0, y: 0 }, radius: kind === 'player' ? 13 : 11, hp: kind === 'enemy' ? 34 : 100, maxHp: kind === 'enemy' ? 34 : 100, damage: kind === 'enemy' ? 8 : 18, color, cooldown: 0 };\n}\n\nexport function tileAt(state: GameState, x: number, y: number) {\n  const tx = Math.floor(x / state.tileSize);\n  const ty = Math.floor(y / state.tileSize);\n  return state.tiles[ty * state.width + tx];\n}\n\nexport function isBlocked(state: GameState, x: number, y: number) {\n  const tile = tileAt(state, x, y);\n  return !tile || tile.wall;\n}\n`
    },
    {
      path: 'src/game/systems.ts',
      content: `import type { Entity, GameState, Vec2 } from './types';\nimport { isBlocked } from './world';\n\nexport interface InputState { keys: Set<string>; pointer: Vec2; attack: boolean; save: boolean; }\n\nexport function updateGame(state: GameState, input: InputState, dt: number) {\n  updatePlayer(state, input, dt);\n  updateEnemies(state, dt);\n  updateProjectiles(state, dt);\n  pickupLoot(state);\n  state.player.cooldown = Math.max(0, state.player.cooldown - dt);\n  if (input.attack && state.player.cooldown <= 0) fireProjectile(state, input.pointer);\n  if (input.save) saveGame(state);\n}\n\nfunction updatePlayer(state: GameState, input: InputState, dt: number) {\n  const speed = 190;\n  const vx = (input.keys.has('d') ? 1 : 0) - (input.keys.has('a') ? 1 : 0);\n  const vy = (input.keys.has('s') ? 1 : 0) - (input.keys.has('w') ? 1 : 0);\n  moveEntity(state, state.player, vx * speed * dt, vy * speed * dt);\n}\n\nfunction updateEnemies(state: GameState, dt: number) {\n  for (const enemy of state.enemies) {\n    if (enemy.hp <= 0) continue;\n    const dx = state.player.pos.x - enemy.pos.x;\n    const dy = state.player.pos.y - enemy.pos.y;\n    const dist = Math.hypot(dx, dy) || 1;\n    enemy.cooldown = Math.max(0, enemy.cooldown - dt);\n    if (dist < 360) moveEntity(state, enemy, (dx / dist) * 92 * dt, (dy / dist) * 92 * dt);\n    if (dist < enemy.radius + state.player.radius + 6 && enemy.cooldown <= 0) {\n      state.player.hp = Math.max(0, state.player.hp - enemy.damage);\n      enemy.cooldown = 0.9;\n      state.messages.unshift(\`Enemy hit you for \${enemy.damage}.\`);\n    }\n  }\n  state.enemies = state.enemies.filter((enemy) => enemy.hp > 0);\n}\n\nfunction updateProjectiles(state: GameState, dt: number) {\n  for (const projectile of state.projectiles) {\n    projectile.pos.x += projectile.vel.x * dt;\n    projectile.pos.y += projectile.vel.y * dt;\n    if (isBlocked(state, projectile.pos.x, projectile.pos.y)) projectile.hp = 0;\n    for (const enemy of state.enemies) {\n      if (enemy.hp <= 0) continue;\n      if (distance(projectile, enemy) < projectile.radius + enemy.radius) {\n        enemy.hp -= projectile.damage;\n        projectile.hp = 0;\n        if (enemy.hp <= 0) {\n          state.xp += 12;\n          if (state.xp >= state.level * 48) { state.level += 1; state.player.maxHp += 12; state.player.hp = state.player.maxHp; state.messages.unshift(\`Level up! Level \${state.level}.\`); }\n        }\n      }\n    }\n  }\n  state.projectiles = state.projectiles.filter((projectile) => projectile.hp > 0);\n}\n\nfunction fireProjectile(state: GameState, pointer: Vec2) {\n  const dx = pointer.x - state.player.pos.x;\n  const dy = pointer.y - state.player.pos.y;\n  const dist = Math.hypot(dx, dy) || 1;\n  state.projectiles.push({ id: crypto.randomUUID(), kind: 'projectile', pos: { ...state.player.pos }, vel: { x: (dx / dist) * 520, y: (dy / dist) * 520 }, radius: 5, hp: 1, maxHp: 1, damage: state.player.damage, color: '#a78bfa', cooldown: 0 });\n  state.player.cooldown = 0.28;\n}\n\nfunction pickupLoot(state: GameState) {\n  for (const item of state.loot) {\n    if (distance(item, state.player) < item.radius + state.player.radius + 5) {\n      item.hp = 0;\n      state.inventory.push('Ancient core');\n      state.messages.unshift('Picked up Ancient core.');\n    }\n  }\n  state.loot = state.loot.filter((item) => item.hp > 0);\n}\n\nfunction moveEntity(state: GameState, entity: Entity, dx: number, dy: number) {\n  const nextX = entity.pos.x + dx;\n  if (!isBlocked(state, nextX, entity.pos.y)) entity.pos.x = nextX;\n  const nextY = entity.pos.y + dy;\n  if (!isBlocked(state, entity.pos.x, nextY)) entity.pos.y = nextY;\n}\n\nfunction distance(a: Entity, b: Entity) { return Math.hypot(a.pos.x - b.pos.x, a.pos.y - b.pos.y); }\n\nexport function saveGame(state: GameState) {\n  localStorage.setItem('forge-game-save', JSON.stringify({ seed: state.seed, player: state.player, inventory: state.inventory, xp: state.xp, level: state.level }));\n  state.messages.unshift('Game saved locally.');\n}\n`
    },
    {
      path: 'src/game/render.ts',
      content: `import type { GameState } from './types';\n\nexport function render(ctx: CanvasRenderingContext2D, state: GameState) {\n  ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);\n  ctx.save();\n  ctx.translate(ctx.canvas.width / 2 - state.player.pos.x, ctx.canvas.height / 2 - state.player.pos.y);\n  for (const tile of state.tiles) {\n    ctx.fillStyle = tile.wall ? '#0f172a' : '#1e293b';\n    ctx.fillRect(tile.x * state.tileSize, tile.y * state.tileSize, state.tileSize - 1, state.tileSize - 1);\n    if (!tile.wall) { ctx.fillStyle = 'rgba(56,189,248,.06)'; ctx.fillRect(tile.x * state.tileSize + 6, tile.y * state.tileSize + 6, 6, 6); }\n  }\n  for (const item of state.loot) drawEntity(ctx, item.pos.x, item.pos.y, item.radius, item.color);\n  for (const projectile of state.projectiles) drawEntity(ctx, projectile.pos.x, projectile.pos.y, projectile.radius, projectile.color);\n  for (const enemy of state.enemies) drawEntity(ctx, enemy.pos.x, enemy.pos.y, enemy.radius, enemy.color, enemy.hp / enemy.maxHp);\n  drawEntity(ctx, state.player.pos.x, state.player.pos.y, state.player.radius, state.player.color, state.player.hp / state.player.maxHp);\n  ctx.restore();\n  drawHud(ctx, state);\n}\n\nfunction drawEntity(ctx: CanvasRenderingContext2D, x: number, y: number, r: number, color: string, hp = 1) {\n  const px = Math.round(x - r);\n  const py = Math.round(y - r);\n  ctx.fillStyle = 'rgba(0,0,0,.35)'; ctx.fillRect(px + 3, py + r * 2 - 2, r * 2, 5);\n  ctx.fillStyle = color;\n  ctx.fillRect(px + 6, py + 2, r * 2 - 12, r * 2 - 4);\n  ctx.fillStyle = '#f8fafc'; ctx.fillRect(px + 9, py + 6, 4, 4); ctx.fillRect(px + r * 2 - 13, py + 6, 4, 4);\n  ctx.fillStyle = 'rgba(255,255,255,.22)'; ctx.fillRect(px + 6, py + 2, r * 2 - 12, 3);\n  ctx.strokeStyle = 'rgba(2,6,23,.85)'; ctx.lineWidth = 2; ctx.strokeRect(px + 6, py + 2, r * 2 - 12, r * 2 - 4);\n  if (hp < 1) {\n    ctx.fillStyle = '#111827'; ctx.fillRect(x - r, y - r - 10, r * 2, 4);\n    ctx.fillStyle = '#22c55e'; ctx.fillRect(x - r, y - r - 10, r * 2 * hp, 4);\n  }\n}\n\nfunction drawHud(ctx: CanvasRenderingContext2D, state: GameState) {\n  ctx.fillStyle = 'rgba(2,6,23,.72)'; ctx.fillRect(12, 12, 330, 116);\n  ctx.fillStyle = '#e0f2fe'; ctx.font = '15px ui-monospace, monospace';\n  ctx.fillText(\`HP \${state.player.hp}/\${state.player.maxHp}   LVL \${state.level}   XP \${state.xp}\`, 28, 40);\n  ctx.fillText(\`Enemies \${state.enemies.length}   Inventory \${state.inventory.length}\`, 28, 64);\n  ctx.fillStyle = '#bae6fd';\n  state.messages.slice(0, 3).forEach((message, index) => ctx.fillText(message.slice(0, 48), 28, 92 + index * 18));\n}\n`
    },
    {
      path: 'src/main.ts',
      content: `import './styles.css';\nimport { createWorld } from './game/world';\nimport { updateGame, type InputState } from './game/systems';\nimport { render } from './game/render';\n\nconst canvas = document.querySelector<HTMLCanvasElement>('#game');\nif (!canvas) throw new Error('Missing canvas');\nconst ctx = canvas.getContext('2d');\nif (!ctx) throw new Error('Missing 2D context');\n\nconst state = createWorld(1337);\nconst input: InputState = { keys: new Set(), pointer: { x: state.player.pos.x + 100, y: state.player.pos.y }, attack: false, save: false };\n\nwindow.addEventListener('keydown', (event) => { input.keys.add(event.key.toLowerCase()); if (event.key.toLowerCase() === 'e') input.save = true; });\nwindow.addEventListener('keyup', (event) => input.keys.delete(event.key.toLowerCase()));\ncanvas.addEventListener('pointermove', (event) => { const rect = canvas.getBoundingClientRect(); input.pointer = { x: state.player.pos.x + event.clientX - rect.left - canvas.width / 2, y: state.player.pos.y + event.clientY - rect.top - canvas.height / 2 }; });\ncanvas.addEventListener('pointerdown', () => { input.attack = true; });\ncanvas.addEventListener('pointerup', () => { input.attack = false; });\n\nlet last = performance.now();\nfunction loop(time: number) {\n  const dt = Math.min(0.033, (time - last) / 1000);\n  last = time;\n  updateGame(state, input, dt);\n  input.save = false;\n  render(ctx!, state);\n  requestAnimationFrame(loop);\n}\nrequestAnimationFrame(loop);\n`
    },
    {
      path: 'src/styles.css',
      content: `html, body { margin: 0; min-height: 100%; background: #020617; color: white; font-family: ui-sans-serif, system-ui; }\nbody { display: grid; place-items: center; overflow: hidden; }\ncanvas { width: min(100vw, 1280px); height: auto; image-rendering: pixelated; border: 1px solid rgba(56,189,248,.35); box-shadow: 0 24px 90px rgba(14,165,233,.18); background: #020617; }\n#hud { position: fixed; right: 16px; bottom: 16px; color: #bae6fd; opacity: .85; }\n`
    },
    {
      path: 'assets/spritesheet.svg',
      content: `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="32" viewBox="0 0 160 32" shape-rendering="crispEdges">\n  <rect width="160" height="32" fill="#020617"/>\n  <g id="player_idle">\n    <rect x="8" y="5" width="16" height="22" fill="#38bdf8"/><rect x="11" y="8" width="4" height="4" fill="#f8fafc"/><rect x="18" y="8" width="4" height="4" fill="#f8fafc"/><rect x="8" y="5" width="16" height="3" fill="#bae6fd"/>\n  </g>\n  <g id="player_walk">\n    <rect x="40" y="5" width="16" height="22" fill="#0ea5e9"/><rect x="43" y="8" width="4" height="4" fill="#f8fafc"/><rect x="50" y="8" width="4" height="4" fill="#f8fafc"/><rect x="40" y="25" width="6" height="4" fill="#075985"/><rect x="50" y="26" width="6" height="3" fill="#075985"/>\n  </g>\n  <g id="enemy_stalker">\n    <rect x="72" y="7" width="16" height="19" fill="#fb7185"/><rect x="75" y="10" width="4" height="4" fill="#450a0a"/><rect x="82" y="10" width="4" height="4" fill="#450a0a"/><rect x="74" y="21" width="12" height="3" fill="#7f1d1d"/>\n  </g>\n  <g id="projectile_arcane">\n    <rect x="107" y="13" width="7" height="7" fill="#a78bfa"/><rect x="109" y="11" width="3" height="11" fill="#c4b5fd"/><rect x="105" y="15" width="11" height="3" fill="#c4b5fd"/>\n  </g>\n  <g id="loot_core">\n    <rect x="135" y="10" width="14" height="14" fill="#facc15"/><rect x="139" y="14" width="6" height="6" fill="#fef08a"/><rect x="135" y="8" width="14" height="2" fill="#854d0e"/>\n  </g>\n</svg>\n`
    },
    {
      path: 'tests/world.test.ts',
      content: `import { describe, expect, it } from 'vitest';\nimport { createWorld, isBlocked } from '../src/game/world';\n\ndescribe('game world systems', () => {\n  it('generates a playable dungeon with player, enemies, and loot', () => {\n    const world = createWorld(42);\n    expect(world.tiles.length).toBe(world.width * world.height);\n    expect(world.enemies.length).toBeGreaterThan(5);\n    expect(world.loot.length).toBeGreaterThan(3);\n    expect(isBlocked(world, world.player.pos.x, world.player.pos.y)).toBe(false);\n  });\n});\n`
    }
  ];
  return {
    kind: 'game',
    techStack: ['Canvas', 'TypeScript', 'Vite', 'Procedural generation', 'Entity systems', 'Vitest'],
    files,
    decisions: [
      { title: 'Use a custom Canvas/TypeScript game loop for the first playable', rationale: 'Canvas has no heavyweight runtime dependency and allows direct implementation of loop, physics, collision, AI, saves, and rendering systems.', consequences: ['The game is immediately inspectable and extensible.', 'Future tasks can swap in Phaser/Pixi/Three when requirements demand it.'] },
      { title: 'Implement real mechanics instead of a static scene', rationale: 'Game requirements demand playable systems, not screenshots.', consequences: ['The scaffold includes movement, collision, enemy AI, combat, loot, progression, and local saves.'] }
    ]
  };
}
