export type ProjectType = 'website' | 'app' | 'game';
export type ForgeFile = { path: string; content: string };

const shell = (title: string, body: string, script = '') => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#07080d;color:#f5f7fb}button{cursor:pointer}</style></head><body>${body}<script>${script}</script></body></html>`;

export function templateProject(type: ProjectType, prompt: string): { files: ForgeFile[]; previewHtml: string; summary: string } {
  const safe = prompt.replace(/[<>]/g, '').slice(0, 100);
  if (type === 'game') {
    const html = shell(safe || 'Forge Game', `<canvas id="game"></canvas><div style="position:fixed;left:16px;top:16px;padding:10px 14px;border-radius:10px;background:#111827aa">WASD / Arrow keys · Score: <b id="score">0</b></div><style>html,body{width:100%;height:100%;overflow:hidden;background:#05070b}canvas{width:100%;height:100%;display:block}</style>`, `const c=document.getElementById('game'),x=c.getContext('2d');let w,h,px,py,score=0,keys={};const enemies=[];function resize(){w=c.width=innerWidth*devicePixelRatio;h=c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);w=innerWidth;h=innerHeight;px=w/2;py=h/2}addEventListener('resize',resize);addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);resize();for(let i=0;i<12;i++)enemies.push({x:Math.random()*w,y:Math.random()*h,r:10+Math.random()*10});function loop(){x.clearRect(0,0,w,h);let s=4;if(keys.w||keys.arrowup)py-=s;if(keys.s||keys.arrowdown)py+=s;if(keys.a||keys.arrowleft)px-=s;if(keys.d||keys.arrowright)px+=s;px=Math.max(14,Math.min(w-14,px));py=Math.max(14,Math.min(h-14,py));x.fillStyle='#8b5cf6';x.beginPath();x.arc(px,py,14,0,7);x.fill();for(const e of enemies){const dx=px-e.x,dy=py-e.y,d=Math.hypot(dx,dy)||1;e.x+=dx/d*.7;e.y+=dy/d*.7;x.fillStyle='#ef4444';x.beginPath();x.arc(e.x,e.y,e.r,0,7);x.fill();if(d<e.r+14){score++;document.getElementById('score').textContent=score;e.x=Math.random()*w;e.y=Math.random()*h}}requestAnimationFrame(loop)}loop();`);
    return {files:[{path:'index.html',content:html}],previewHtml:html,summary:'Playable Canvas survival game with movement, enemies, collision scoring and responsive rendering.'};
  }
  if (type === 'app') {
    const html = shell(safe || 'Forge App', `<main style="max-width:1000px;margin:auto;padding:48px 20px"><nav style="display:flex;justify-content:space-between;align-items:center"><b style="font-size:22px">Forge App</b><button id="add" style="padding:10px 14px;border:0;border-radius:9px;background:#8b5cf6;color:white">Add item</button></nav><h1 style="font-size:42px;margin-bottom:8px">Your workspace</h1><p style="color:#9ca3af">A functional local-first dashboard generated from: ${safe}</p><section id="items" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-top:30px"></section></main>`, `const root=document.getElementById('items');let items=['Welcome','Build something','Ship it'];function render(){root.innerHTML=items.map((v,i)=>'<article style="padding:20px;border:1px solid #273044;border-radius:14px;background:#0d111a"><b>'+v+'</b><p style="color:#9ca3af">Item '+(i+1)+'</p><button onclick="items.splice(${0},1);render()" style="padding:7px 10px;border-radius:7px;border:1px solid #374151;background:#111827;color:white">Remove</button></article>').join('')}document.getElementById('add').onclick=()=>{items.push('New item '+(items.length+1));render()};render();`);
    return {files:[{path:'index.html',content:html}],previewHtml:html,summary:'Functional responsive dashboard with persistent in-session item management and interactive controls.'};
  }
  const html = shell(safe || 'Forge Website', `<header style="padding:24px 6%;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #202635"><b style="font-size:22px">Forge</b><nav><a href="#features" style="color:#c4b5fd;margin:12px">Features</a><a href="#start" style="color:#c4b5fd">Get started</a></nav></header><main><section style="min-height:70vh;display:grid;place-items:center;text-align:center;padding:60px 20px;background:radial-gradient(circle at 50% 20%,#3b1b7855,transparent 55%)"><div><span style="color:#a78bfa;font-weight:700">BUILT WITH FORGE AI</span><h1 style="font-size:clamp(48px,8vw,92px);line-height:.95;margin:18px 0">${safe || 'A website that feels alive.'}</h1><p style="font-size:20px;color:#9ca3af;max-width:680px;margin:auto">A polished, responsive starting point that you can keep iterating with Forge.</p><button id="start" style="margin-top:28px;padding:14px 20px;border:0;border-radius:10px;background:#8b5cf6;color:white;font-weight:700">Start building</button></div></section><section id="features" style="max-width:1000px;margin:auto;padding:80px 20px;display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px"><article style="padding:24px;border:1px solid #202635;border-radius:15px"><h3>Responsive</h3><p style="color:#9ca3af">Designed to adapt from phones to large displays.</p></article><article style="padding:24px;border:1px solid #202635;border-radius:15px"><h3>Interactive</h3><p style="color:#9ca3af">Buttons and navigation are wired up, not decorative.</p></article><article style="padding:24px;border:1px solid #202635;border-radius:15px"><h3>Extensible</h3><p style="color:#9ca3af">Use the AI mode to turn this starter into a real product.</p></article></section></main><script>document.getElementById('start').onclick=()=>document.getElementById('features').scrollIntoView({behavior:'smooth'})</script>`);
  return {files:[{path:'index.html',content:html}],previewHtml:html,summary:'Responsive multi-section landing page with navigation, CTA interaction and polished visual structure.'};
}