import fs from 'node:fs';
import path from 'node:path';
import { DatabaseTable, DatabaseTableColumn } from '../../shared/types.js';
import { createId, nowIso, safeJoin } from '../security.js';
import { store } from '../store.js';
import { projectService } from './projectService.js';

const TABLES_TABLE = 'database-tables';

function sqlIdentifier(name: string) {
  if (!/^[a-z][a-z0-9_]*$/i.test(name)) throw new Error(`Invalid SQL identifier: ${name}`);
  return name.toLowerCase();
}

function columnSql(column: DatabaseTableColumn) {
  const pieces = [`  ${sqlIdentifier(column.name)} ${column.type}`];
  if (column.primaryKey) pieces.push('primary key');
  if (!column.nullable) pieces.push('not null');
  if (column.unique) pieces.push('unique');
  if (column.defaultValue) pieces.push(`default ${column.defaultValue}`);
  if (column.references) pieces.push(`references ${sqlIdentifier(column.references.table)}(${sqlIdentifier(column.references.column)})`);
  return pieces.join(' ');
}

export class DatabaseService {
  listTables(projectId: string) {
    return store.read<DatabaseTable[]>(TABLES_TABLE, []).filter((table) => table.projectId === projectId);
  }

  upsertTable(input: {
    projectId: string;
    name: string;
    description?: string;
    columns: DatabaseTableColumn[];
    rlsEnabled?: boolean;
    policies?: string[];
    indexes?: string[];
  }) {
    const timestamp = nowIso();
    const name = sqlIdentifier(input.name);
    let table = this.listTables(input.projectId).find((item) => item.name === name);
    if (!table) {
      table = {
        id: createId('table'),
        projectId: input.projectId,
        name,
        description: input.description || '',
        columns: input.columns,
        rlsEnabled: input.rlsEnabled ?? true,
        policies: input.policies || [],
        indexes: input.indexes || [],
        createdAt: timestamp,
        updatedAt: timestamp
      };
    } else {
      table = {
        ...table,
        description: input.description ?? table.description,
        columns: input.columns,
        rlsEnabled: input.rlsEnabled ?? table.rlsEnabled,
        policies: input.policies ?? table.policies,
        indexes: input.indexes ?? table.indexes,
        updatedAt: timestamp
      };
    }
    store.update<DatabaseTable[]>(TABLES_TABLE, [], (tables) => [table!, ...tables.filter((item) => item.id !== table!.id)]);
    const migrationPath = this.writeMigration(table);
    projectService.addMemory(input.projectId, 'database', `Database table ${name}`, `Migration generated at ${migrationPath}.`, ['database', 'migration', name]);
    return { table, migrationPath };
  }

  writeMigration(table: DatabaseTable) {
    const project = projectService.getProject(table.projectId);
    const migrationsDir = safeJoin(project.rootPath, 'supabase/migrations');
    fs.mkdirSync(migrationsDir, { recursive: true });
    const stamp = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
    const fileName = `${stamp}_create_${table.name}.sql`;
    const filePath = path.join(migrationsDir, fileName);
    const sql = this.generateCreateTableSql(table);
    fs.writeFileSync(filePath, sql, 'utf8');
    return path.relative(project.rootPath, filePath);
  }

  generateCreateTableSql(table: DatabaseTable) {
    const tableName = sqlIdentifier(table.name);
    const columnDefs = table.columns.map(columnSql).join(',\n');
    const lines = [
      `-- Generated by Forge AI. Review before applying to production.`,
      `create table if not exists public.${tableName} (`,
      columnDefs,
      `);`,
      ''
    ];
    for (const index of table.indexes) {
      lines.push(`create index if not exists ${sqlIdentifier(`${tableName}_${index}_idx`)} on public.${tableName} (${sqlIdentifier(index)});`);
    }
    if (table.rlsEnabled) {
      lines.push('', `alter table public.${tableName} enable row level security;`);
      if (table.policies.length) {
        lines.push(...table.policies);
      } else {
        lines.push(
          `-- Default safe policy: authenticated users can read their own rows when an owner_id column exists.`,
          `do $$ begin`,
          `  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = '${tableName}' and column_name = 'owner_id') then`,
          `    create policy "${tableName}_owner_select" on public.${tableName} for select using (auth.uid() = owner_id);`,
          `  end if;`,
          `exception when duplicate_object then null; end $$;`
        );
      }
    }
    return `${lines.join('\n')}\n`;
  }

  inspectMigrations(projectId: string) {
    const project = projectService.getProject(projectId);
    const dir = safeJoin(project.rootPath, 'supabase/migrations');
    if (!fs.existsSync(dir)) return [];
    return fs
      .readdirSync(dir)
      .filter((file) => file.endsWith('.sql'))
      .sort()
      .map((file) => ({ path: path.relative(project.rootPath, path.join(dir, file)), content: fs.readFileSync(path.join(dir, file), 'utf8') }));
  }
}

export const databaseService = new DatabaseService();
